(function(){
var schema = {
  "name":       String,
  "uuid":       String,
  "pvcid":      String,
  "addr":       String,
  "type":       String,
  "role":       String,
  "created_at": { type: Number, default: Date.now },
  "updated_at": Number,
  "status":     { type: Number, default: 0 }
};
// type in [ 'was', 'db2' ]
// type = 'db2', role in ['master', 'slave']
// type = 'was', role in ['cell', 'stand']
// uuid is PK,   pvcid is unique, addr is unique
// status = 0
// uuid generated by java prog.
// powervc list => pvcid not exists? => delete pvcid ( service TODO )
module.exports = schema;
})();
